import type { ChartDefinition } from "../types";

export function isTemplate(chart: ChartDefinition): boolean {
  return chart.id.startsWith("template:");
}

export const CHART_TEMPLATES: ChartDefinition[] = [
  {
    id: "template:output-over-time",
    name: "Output Over Time",
    mark_type: "dot",
    y_fields: [{ field: "total_work", side: "left" }],
    group_by: null,
    filters: [],
    x_axis_mode: "date",
    x_axis_field: null,
    x_axis_sequential: false,
    agg_function: null,
    created_at: 0,
    updated_at: 0,
  },
  {
    id: "template:output-by-duration",
    name: "Output by Duration",
    mark_type: "dot",
    y_fields: [{ field: "total_work", side: "left" }],
    group_by: "duration_seconds",
    filters: [],
    x_axis_mode: "date",
    x_axis_field: null,
    x_axis_sequential: false,
    agg_function: null,
    created_at: 0,
    updated_at: 0,
  },
  {
    id: "template:avg-output-by-instructor",
    name: "Avg Output by Instructor",
    mark_type: "dot",
    y_fields: [{ field: "avg_output", side: "left" }],
    group_by: "instructor",
    filters: [],
    x_axis_mode: "date",
    x_axis_field: null,
    x_axis_sequential: false,
    agg_function: null,
    created_at: 0,
    updated_at: 0,
  },
  {
    id: "template:heart-rate-trend",
    name: "Heart Rate Trend",
    mark_type: "line",
    y_fields: [{ field: "avg_heart_rate", side: "left" }],
    group_by: null,
    filters: [],
    x_axis_mode: "date",
    x_axis_field: null,
    x_axis_sequential: false,
    agg_function: null,
    created_at: 0,
    updated_at: 0,
  },
  {
    id: "template:cadence-vs-resistance",
    name: "Cadence vs Resistance",
    mark_type: "dot",
    y_fields: [
      { field: "avg_cadence", side: "left" },
      { field: "avg_resistance", side: "right" },
    ],
    group_by: null,
    filters: [],
    x_axis_mode: "date",
    x_axis_field: null,
    x_axis_sequential: false,
    agg_function: null,
    created_at: 0,
    updated_at: 0,
  },
  {
    id: "template:calories-by-discipline",
    name: "Calories by Discipline",
    mark_type: "dot",
    y_fields: [{ field: "calories", side: "left" }],
    group_by: "discipline",
    filters: [],
    x_axis_mode: "date",
    x_axis_field: null,
    x_axis_sequential: false,
    agg_function: null,
    created_at: 0,
    updated_at: 0,
  },
  {
    id: "template:strive-score-trend",
    name: "Strive Score Trend",
    mark_type: "line",
    y_fields: [{ field: "strive_score", side: "left" }],
    group_by: null,
    filters: [],
    x_axis_mode: "date",
    x_axis_field: null,
    x_axis_sequential: false,
    agg_function: null,
    created_at: 0,
    updated_at: 0,
  },
  {
    id: "template:monthly-output-avg",
    name: "Monthly Output (avg)",
    mark_type: "bar",
    y_fields: [{ field: "avg_output", side: "left" }],
    group_by: null,
    filters: [],
    x_axis_mode: "month",
    x_axis_field: null,
    x_axis_sequential: false,
    agg_function: "avg",
    created_at: 0,
    updated_at: 0,
  },
  {
    id: "template:output-by-instructor-avg",
    name: "Output by Instructor (avg)",
    mark_type: "bar",
    y_fields: [{ field: "avg_output", side: "left" }],
    group_by: null,
    filters: [],
    x_axis_mode: "category",
    x_axis_field: "instructor",
    x_axis_sequential: false,
    agg_function: "avg",
    created_at: 0,
    updated_at: 0,
  },
];
