#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
ROOT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
OUTPUT="$ROOT_DIR/docs/SCHEMA.md"

mkdir -p "$ROOT_DIR/docs"

ERD=$(cd "$ROOT_DIR/src-tauri" && cargo run --bin schema-export 2>/dev/null)

cat > "$OUTPUT" <<EOF
# Database Schema

> Auto-generated by \`scripts/generate-schema-erd.sh\`. Do not edit manually.

\`\`\`mermaid
$ERD
\`\`\`
EOF

echo "Wrote $OUTPUT"
